### ISSUE TITLE
Database setup

### ISSUE THREAD

**Issue by anonrig** [anonrig/calendar#6]
We need to select a database provider and a good ORM with good DX for our backend. 

## Providers

- [x] Planetscale
- [ ] Neon

## ORMs for Rust

- [x] https://diesel.rs
- [ ] https://www.sea-ql.org/SeaORM/

**Comment by anonrig** [comment]
@steveklabnik what are your thoughts on ORMs for Rust?

**Comment by steveklabnik** [comment]
Hello! Yes meant to weigh in last night, but stuff came up, thanks for the ping :)

Diesel is one of the longest running projects. It was created by an expert in the space. It's good. But one of its neatest aspects, that it implements logic in the type system, means that the types can get gnarly, and that compile times can get higher. Diesel also historically had a weird async story, unsure what's up with that.

I have not used SeaORM. However, I do know that it is built on top of sqlx, which is the library I would be investigating if I were starting a new service today. this is partially due to diesel's complexity, but also that i already know it, and don't know sqlx well, and have heard many good things. sqlx has you write SQL directly, so it's a bit lower level than you may be after.

These two are certainly the big hitters in the space. Can't go too wrong with either of them.

I also know of someone working on a new ORM project that I expect to be good, but it's not ready to be used just yet.

**Comment by anonrig** [comment]
@lexor did a fantastic job on this. Thank you @steveklabnik for your amazing input as always!
